'''Read and write FASTA-format DNA, RNA, or Peptide sequences.'''
import coral as cr
import re


def parse_fasta(handle, seq_type='DNA'):
    '''Read in a single record from a FASTA file.

    :param handle: An open file handle of that type generated by open().
    :type handle: file
    :param seq_type: Name of the sequence container to use as the output:
                      \'DNA\', \'ssDNA\', \'RNA\', or \'Peptide\'.
    :type seq_type: str

    '''
    # FASTA files are repeats of two elements: a description (starting with >)
    # and a potentially multi-line sequence.
    if seq_type == 'DNA':
        container = cr.DNA
    elif seq_type == 'ssDNA':
        container = cr.ssDNA
    elif seq_type == 'RNA':
        container = cr.RNA
    elif seq_type == 'Peptide':
        container = cr.Peptide
    else:
        raise ValueError('seq_type must be DNA, ssDNA, RNA, or Peptide')

    read = handle.read()
    seq = container('')
    seq_search = re.search('^(?!>)(.+?)(?=>|\Z)', read,
                           flags=re.S | re.M).group(1)
    seq += container(''.join(seq_search.split('\n')))
    seq.description = re.search('^>(.*)', read).group(1)
    seq.name = seq.description

    return seq
